name: Gym Class Scraper

on:
  schedule:
    # Run every 2 hours starting at 6 AM AEST (8 PM UTC previous day)
    # AEST = UTC+10, so 6am AEST = 8pm UTC (previous day)
    # Times: 6am, 8am, 10am, 12pm, 2pm, 4pm, 6pm, 8pm, 10pm AEST
    # UTC:   8pm, 10pm, 12am, 2am, 4am, 6am, 8am, 10am, 12pm (previous/same day)
    - cron: '0 20,22,0,2,4,6,8,10,12 * * *'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    # Add timeout to ensure it doesn't run longer than 1 hour
    timeout-minutes: 60
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libdrm2 \
            libxkbcommon0 \
            libgbm1 \
            libxrandr2 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libcups2 \
            libxss1 \
            libxtst6 \
            fonts-liberation \
            libappindicator3-1 \
            xdg-utils
      
      - name: Run scraper
        env:
          GYM_USERNAME: ${{ secrets.GYM_USERNAME }}
          GYM_PASSWORD: ${{ secrets.GYM_PASSWORD }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node scraper.js
      
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-logs
          path: |
            *.log
            screenshots/*.png
          retention-days: 7